# version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend/vite-project
    ports:
      - "5173:5173"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: anandshukla$15
      MYSQL_DATABASE: ai_dashboard
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
