services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env
    command: npm run dev

  frontend:
    build: ./frontend/vite-project
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/vite-project:/app
      - /app/node_modules
    command: npm run dev

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: anandshukla$15
      MYSQL_DATABASE: ai_dashboard
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
